import type {
	AgentClientEvent,
	AgentInstanceLocator,
	AgentRole,
	ApproveRequirementInput,
	ArchiveWorkItemInput,
	CodePIddyClientApi,
	CreateAgentInput,
	CreateWorkItemInput,
	ExtensionUiResponseInput,
	ForkAgentSessionInput,
	InvokeAgentBuiltinCommandInput,
	PermissionDefaults,
	RenameWorkItemInput,
	ResetAgentInput,
	RoleModelDefault,
	SendAgentPromptInput,
	SetAgentModelInput,
	SetAgentScopedModelsInput,
	SetAgentThinkingInput,
	SetRoleSkillAssignmentsInput,
} from "@codepiddy/shared";
import { contextBridge, ipcRenderer } from "electron";

const channels = {
	abortAgent: "codepiddy:agent:abort",
	reconnectAgent: "codepiddy:agent:reconnect",
	compactAgent: "codepiddy:agent:compact",
	invokeAgentBuiltinCommand: "codepiddy:agent:command:invoke",
	cloneAgentSession: "codepiddy:agent:session:clone",
	getAgentSessionSnapshot: "codepiddy:agent:session:get",
	forkAgentSession: "codepiddy:agent:session:fork",
	resetAgent: "codepiddy:agent:reset",
	activateAgent: "codepiddy:agent:activate",
	agentEvent: "codepiddy:agent:event",
	approveRequirement: "codepiddy:work-item:approve-requirement",
	archiveWorkItem: "codepiddy:work-item:archive",
	createAgent: "codepiddy:agent:create",
	createWorkItem: "codepiddy:work-item:create",
	renameWorkItem: "codepiddy:work-item:rename",
	deleteWorkItem: "codepiddy:work-item:delete",
	getAgentModelSelection: "codepiddy:agent:model:get",
	getAgentScopedModels: "codepiddy:agent:scoped-models:get",
	getAgentCommands: "codepiddy:agent:commands:get",
	getProjectWriteLeaseStatus: "codepiddy:write-lease:get",
	clearStaleProjectWriteLease: "codepiddy:write-lease:clear-stale",
	setAgentModel: "codepiddy:agent:model:set",
	setAgentScopedModels: "codepiddy:agent:scoped-models:set",
	setAgentThinking: "codepiddy:agent:thinking:set",
	listRecentProjects: "codepiddy:project:recent:list",
	getStartupProject: "codepiddy:project:startup",
	closeProject: "codepiddy:project:close",
	openProject: "codepiddy:project:open",
	openRecentProject: "codepiddy:project:recent:open",
	forgetRecentProject: "codepiddy:project:recent:forget",
	openWorkItemFolder: "codepiddy:work-item:open-folder",
	getProjectUiState: "codepiddy:ui:project:get",
	saveProjectUiState: "codepiddy:ui:project:save",
	getAgentUiState: "codepiddy:ui:agent:get",
	saveAgentUiState: "codepiddy:ui:agent:save",
	refreshProject: "codepiddy:project:refresh",
	restoreWorkItem: "codepiddy:work-item:restore",
	respondToExtensionUi: "codepiddy:agent:extension-ui-response",
	getPendingPermissionRequest: "codepiddy:agent:permission:get-pending",
	settingsClearTavily: "codepiddy:settings:tavily:clear",
	settingsListSkills: "codepiddy:settings:skills:list",
	settingsGetRoleSkills: "codepiddy:settings:role-skills:get",
	settingsSetRoleSkills: "codepiddy:settings:role-skills:set",
	settingsOpenPiConfig: "codepiddy:settings:pi-config:open",
	settingsOpenProjectSkills: "codepiddy:settings:project-skills:open",
	settingsGetRoleDefaults: "codepiddy:settings:role-models:get",
	settingsGetPermissions: "codepiddy:settings:permissions:get",
	settingsSetRoleDefault: "codepiddy:settings:role-models:set",
	settingsSetPermissions: "codepiddy:settings:permissions:set",
	settingsClearRoleDefault: "codepiddy:settings:role-models:clear",
	settingsSaveTavily: "codepiddy:settings:tavily:save",
	settingsStatus: "codepiddy:settings:status",
	searchProjectFiles: "codepiddy:project:files:search",
	sendAgentPrompt: "codepiddy:agent:prompt",
} as const;

const api: CodePIddyClientApi = {
	listRecentProjects: () => ipcRenderer.invoke(channels.listRecentProjects),
	getStartupProject: () => ipcRenderer.invoke(channels.getStartupProject),
	closeProject: (projectRoot: string) => ipcRenderer.invoke(channels.closeProject, projectRoot),
	openRecentProject: (projectRoot: string) => ipcRenderer.invoke(channels.openRecentProject, projectRoot),
	forgetRecentProject: (projectRoot: string) => ipcRenderer.invoke(channels.forgetRecentProject, projectRoot),
	openProject: () => ipcRenderer.invoke(channels.openProject),
	refreshProject: (projectRoot) => ipcRenderer.invoke(channels.refreshProject, projectRoot),
	createWorkItem: (input: CreateWorkItemInput) => ipcRenderer.invoke(channels.createWorkItem, input),
	approveRequirement: (input: ApproveRequirementInput) => ipcRenderer.invoke(channels.approveRequirement, input),
	archiveWorkItem: (input: ArchiveWorkItemInput) => ipcRenderer.invoke(channels.archiveWorkItem, input),
	restoreWorkItem: (input: ArchiveWorkItemInput) => ipcRenderer.invoke(channels.restoreWorkItem, input),
	renameWorkItem: (input: RenameWorkItemInput) => ipcRenderer.invoke(channels.renameWorkItem, input),
	deleteWorkItem: (input: ArchiveWorkItemInput) => ipcRenderer.invoke(channels.deleteWorkItem, input),
	openWorkItemFolder: (input: ArchiveWorkItemInput) => ipcRenderer.invoke(channels.openWorkItemFolder, input),
	getProjectUiState: (projectRoot: string) => ipcRenderer.invoke(channels.getProjectUiState, projectRoot),
	saveProjectUiState: (state) => ipcRenderer.invoke(channels.saveProjectUiState, state),
	getAgentUiState: (agentInstanceId: string) => ipcRenderer.invoke(channels.getAgentUiState, agentInstanceId),
	saveAgentUiState: (state) => ipcRenderer.invoke(channels.saveAgentUiState, state),
	getAgentModelSelection: (input: AgentInstanceLocator) => ipcRenderer.invoke(channels.getAgentModelSelection, input),
	getAgentScopedModels: (input: AgentInstanceLocator) => ipcRenderer.invoke(channels.getAgentScopedModels, input),
	getAgentCommands: (input: AgentInstanceLocator) => ipcRenderer.invoke(channels.getAgentCommands, input),
	getProjectWriteLeaseStatus: (projectId: string) =>
		ipcRenderer.invoke(channels.getProjectWriteLeaseStatus, projectId),
	clearStaleProjectWriteLease: (projectId: string) =>
		ipcRenderer.invoke(channels.clearStaleProjectWriteLease, projectId),
	setAgentModel: (input: SetAgentModelInput) => ipcRenderer.invoke(channels.setAgentModel, input),
	setAgentScopedModels: (input: SetAgentScopedModelsInput) => ipcRenderer.invoke(channels.setAgentScopedModels, input),
	setAgentThinking: (input: SetAgentThinkingInput) => ipcRenderer.invoke(channels.setAgentThinking, input),
	createAgent: (input: CreateAgentInput) => ipcRenderer.invoke(channels.createAgent, input),
	activateAgent: (input: AgentInstanceLocator) => ipcRenderer.invoke(channels.activateAgent, input),
	sendAgentPrompt: (input: SendAgentPromptInput) => ipcRenderer.invoke(channels.sendAgentPrompt, input),
	abortAgent: (input: AgentInstanceLocator) => ipcRenderer.invoke(channels.abortAgent, input),
	reconnectAgent: (input: AgentInstanceLocator) => ipcRenderer.invoke(channels.reconnectAgent, input),
	compactAgent: (input: AgentInstanceLocator) => ipcRenderer.invoke(channels.compactAgent, input),
	invokeAgentBuiltinCommand: (input: InvokeAgentBuiltinCommandInput) =>
		ipcRenderer.invoke(channels.invokeAgentBuiltinCommand, input),
	cloneAgentSession: (input: AgentInstanceLocator) => ipcRenderer.invoke(channels.cloneAgentSession, input),
	getAgentSessionSnapshot: (input: AgentInstanceLocator) =>
		ipcRenderer.invoke(channels.getAgentSessionSnapshot, input),
	forkAgentSession: (input: ForkAgentSessionInput) => ipcRenderer.invoke(channels.forkAgentSession, input),
	resetAgent: (input: ResetAgentInput) => ipcRenderer.invoke(channels.resetAgent, input),
	respondToExtensionUi: (input: ExtensionUiResponseInput) => ipcRenderer.invoke(channels.respondToExtensionUi, input),
	getPendingPermissionRequest: (input: AgentInstanceLocator) =>
		ipcRenderer.invoke(channels.getPendingPermissionRequest, input),
	searchProjectFiles: (projectRoot: string, query: string) =>
		ipcRenderer.invoke(channels.searchProjectFiles, projectRoot, query),
	getSettingsStatus: () => ipcRenderer.invoke(channels.settingsStatus),
	getPermissionDefaults: () => ipcRenderer.invoke(channels.settingsGetPermissions),
	setPermissionDefaults: (input: PermissionDefaults) => ipcRenderer.invoke(channels.settingsSetPermissions, input),
	saveTavilyApiKey: (apiKey: string) => ipcRenderer.invoke(channels.settingsSaveTavily, apiKey),
	clearTavilyApiKey: () => ipcRenderer.invoke(channels.settingsClearTavily),
	listAgentSkills: (projectRoot?: string) => ipcRenderer.invoke(channels.settingsListSkills, projectRoot),
	getRoleSkillAssignments: () => ipcRenderer.invoke(channels.settingsGetRoleSkills),
	setRoleSkillAssignments: (input: SetRoleSkillAssignmentsInput) =>
		ipcRenderer.invoke(channels.settingsSetRoleSkills, input),
	openPiConfigFolder: () => ipcRenderer.invoke(channels.settingsOpenPiConfig),
	openProjectSkillsFolder: (projectRoot: string) =>
		ipcRenderer.invoke(channels.settingsOpenProjectSkills, projectRoot),
	getRoleModelDefaults: () => ipcRenderer.invoke(channels.settingsGetRoleDefaults),
	setRoleModelDefault: (input: RoleModelDefault) => ipcRenderer.invoke(channels.settingsSetRoleDefault, input),
	clearRoleModelDefault: (role: AgentRole) => ipcRenderer.invoke(channels.settingsClearRoleDefault, role),
	onAgentEvent: (listener) => {
		const handler = (_event: Electron.IpcRendererEvent, event: AgentClientEvent) => listener(event);
		ipcRenderer.on(channels.agentEvent, handler);
		return () => ipcRenderer.removeListener(channels.agentEvent, handler);
	},
};

contextBridge.exposeInMainWorld("codepiddy", api);
